module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Orders", [
      {
        customer: "Frank",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "David",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Jake",
        dispensary: "CureStation",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Henry",
        dispensary: "GreenLight",
        status: "DISPATCHED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Cindy",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Nina",
        dispensary: "LeafLine",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "LeafLine",
        status: "PLACED",
        borough: "BROOKLYN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Alice",
        dispensary: "CureStation",
        status: "PLACED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Jake",
        dispensary: "LeafLine",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "HighWay",
        status: "DISPATCHED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Bob",
        dispensary: "420Zone",
        status: "DISPATCHED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "GreenWave",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Oscar",
        dispensary: "GreenLight",
        status: "DISPATCHED",
        borough: "BROOKLYN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "GreenWave",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "CureStation",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Jake",
        dispensary: "420Zone",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Henry",
        dispensary: "GreenWave",
        status: "PLACED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "GreenMart",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Jake",
        dispensary: "420Zone",
        status: "PLACED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "LeafLine",
        status: "DISPATCHED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Liam",
        dispensary: "CureStation",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "David",
        dispensary: "Nature’s Cure",
        status: "DISPATCHED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "GreenWave",
        status: "DISPATCHED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "CureStation",
        status: "PLACED",
        borough: "BROOKLYN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "David",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Nina",
        dispensary: "GreenWave",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "Herb Spot",
        status: "PLACED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "GreenLight",
        status: "PLACED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "HighWay",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Alice",
        dispensary: "Nature’s Cure",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Grace",
        dispensary: "GreenMart",
        status: "DISPATCHED",
        borough: "STATEN_ISLAND",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Liam",
        dispensary: "GreenLight",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "David",
        dispensary: "LeafLine",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Ivy",
        dispensary: "OrganicMed",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Cindy",
        dispensary: "GreenWave",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Cindy",
        dispensary: "CureStation",
        status: "DISPATCHED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "HighWay",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "Herb Spot",
        status: "DISPATCHED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Eva",
        dispensary: "GreenMart",
        status: "PLACED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Frank",
        dispensary: "420Zone",
        status: "PLACED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Eva",
        dispensary: "GreenWave",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Ivy",
        dispensary: "GreenWave",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Oscar",
        dispensary: "GreenMart",
        status: "PLACED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Paul",
        dispensary: "GreenLight",
        status: "DISPATCHED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Oscar",
        dispensary: "OrganicMed",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Ivy",
        dispensary: "420Zone",
        status: "DISPATCHED",
        borough: "BROOKLYN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Liam",
        dispensary: "Herb Spot",
        status: "DISPATCHED",
        borough: "BRONX",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "Mia",
        dispensary: "OrganicMed",
        status: "DISPATCHED",
        borough: "QUEENS",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        customer: "David",
        dispensary: "GreenWave",
        status: "PLACED",
        borough: "MANHATTAN",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Orders", null, {});
  },
};
